skills_list = ["Google Cloud Platform (GCP)", "Travis CI", "Ethereum", "ELK Stack", "Keras", "Pascal", "Scheme", "Apache Spark", 
"Forth", "MXNet", "Matplotlib", "Bash", "Firestore", "Microservices Architecture", "CouchDB", "FastAPI", "Kotlin Multiplatform", 
"InfluxDB", "Data Warehousing", "Storybook", "Bootstrap","RAG (Retrieval-Augmented Generation)", "Bitbucket", "Groovy", 
"React Native", "Integration Testing", "Kubernetes", "Code Review Practices", "GitLab CI/CD", "Linkerd", "Security",
"Auditing", "Google Cloud Functions", "GraphQL Subscriptions", "GSAP", "Perl", "Gatsby", "Kanban", "Dlib", "ONNX", "Zig", 
"Caffe", "jQuery", "Python", "Spring", "JavaScript", "Racket", "Mocha", "Ruby on Rails", "Mendix", "OpenAPI (Swagger)", 
"Crystal", "Web Components", "BigQuery", "OWASP", "Zurb Foundation", "PHP", "PyCharm", "IDS/IPS", "MariaDB", "Redshift", 
"Phoenix (Elixir)", "Express.js", "VHDL", "CI/CD Pipelines", "SVG Animations", "Agile Methodologies", "Shell scripting", 
".NET", "Network Security", "Vuforia", "Scrum", "Salesforce", "Apache Ant", "H2O.ai", "Selenium WebDriver", "CatBoost", 
"Lottie", "Elm", "TimescaleDB", "Karate", "Hadoop", "Dplyr", "Nmap", "Wireshark", "QlikView", "C#", "JUnit", "Cloudflare Workers", 
"Laravel", "Vyper", "Svelte", "Nuxt.js", "Machine Learning", "Tailwind CSS", "SQLite", "Visual Basic", "Consul", "SQL Server", 
"Burp Suite", "Azure DevOps", "Ada", "NetBeans", "MongoDB", "SIEM", "Clean Code", "Zustand", "Cocos2d", "Teradata", "C++", 
"Static Code Analysis", "Three.js", "Django", "ESLint", "Helm", "RSpec", "Docker", "Amazon DynamoDB", "WebStorm", "Terraform", 
"Ethical Hacking", "Framer Motion", "Speech Recognition", "IBM Cloud", "DynamoDB", "Chef", "Haskell", "Smalltalk", "Theano", 
"LangChain", "SOLID Principles", "Godot", "Microsoft Azure", "Clojure", "Istio", "Pandas", "Elixir", "Julia", "PyTest", 
"Confluence", "Apache Cassandra", "Hyperledger", "Redis", "TypeScript", "C", "ARCore", "Metasploit", "Reinforcement Learning", 
"Hive", "TDD", "Design Patterns", "XGBoost", "CodeIgniter", "Monorepo Management", "Jest", "Firewalls", "Chai", "Apache Pulsar", 
"NLTK", "CSS", "Kotlin", "JAX", "D3.js", "Xcode", "Flask", "NestJS", "CloudFormation", "HashiCorp Vault", "Node.js", "Bulma", 
"AngularJS", "DVC", "NUnit", "ALGOL", "Apache Mahout", "Deeplearning4j", "Threat Modeling", "Alibaba Cloud", 
"Functional Programming", "Jasmine", "Grunt", "TravisCI", "PostgreSQL", "MS SQL Server", "Ionic", "Dart", "HTML", 
"Google Cloud Firestore", "GitHub", "Trello", "gRPC", "Chakra UI", "Databricks", "AWS Lambda", "R", "Tcl", "Assembly (x86)", 
"Erlang", "Neo4j", "Yarn", "Data Modeling", "Software Estimation", "Flutter", "Git", "Scala", "Asana", "Visual Studio", "Unity", 
"Flink", "Refactoring Techniques", "NumPy", "MLflow", "iOS", "GitLab", "Mithril", "Tableau", "Spring Boot", "Swift", "Torch", 
"Prettier", "Rust", "Smart Contracts", "Jira", "Penetration Testing", "RESTful API Design", "Grafana", "Elasticsearch", "Bubble", 
"OpenCV", "Web3.js", "Pulumi", "MATLAB", "Scikit-learn", "Next.js", "Vite", "Fortran", "Java", "Firebase Realtime Database", 
"Pair Programming", "Postman", "OutSystems", "Material-UI", "ARKit", "MySQL", "Ethers.js", "Cryptography", "COBOL", "SwiftUI", 
"Apache Kafka", "AWS Fargate", "Solidity", "Meteor", "Apache Flink", "Verilog", "OpenAI APIs", "Objective-C", "SOC Operations", 
"Cucumber", "SourceTree", "Prolog", "Cassandra", "Redux", "CircleCI", "SAP Cloud", "Oracle Database", "Computer Vision", 
"TensorFlow", "Apache Hive", "OWASP ZAP", "Symfony", "TestNG", "OpenAI Gym", "ETL Pipelines", "Apache Airflow", "Hibernate", 
"Kali Linux", "BDD", "Snowflake", "GitHub Actions", "AWS", "Sublime Text", "Data Lakes", "Natural Language Processing (NLP)", 
"Unit Testing", "SpaCy", "Cypress", "E2E Testing", "Webpack", "ArgoCD", "Ember.js", "Angular", "Selenium", "Backbone.js", "Ruby", 
"WebSockets", "Vue.js", "Unreal Engine", "Appium", "React", "Ansible", "Eclipse", "Go", "Power BI", "Handlebars.js", 
"Visual Studio Code", "Knockout.js", "Deep Learning", "Object-Oriented Programming (OOP)", "Puppet", "Hugging Face Transformers", 
"Lisp", "Android", "ASP.NET Core", "Lua", "Sybase", "Apache NiFi", "F#", "Prometheus", "Amazon Web Services (AWS)", "Plotly", 
"Apache Maven", "PyTorch", "Oracle Cloud", "Jenkins", "LightGBM", "VMware Cloud", "Nest.Js","Electron.js", "Molecular.js", "node"
]


skills_expansions = {
    "gcp": ["GCP", "Google Cloud", "Google Cloud Platform", "Google Cloud Platform (GCP)"],
    "travisci": ["Travis", "TravisCI", "Travis CI"],
    "ASP.NET Core": ["ASP . NET Core"],
    "ethereum": ["Ethereum", "ETH", "ethereum"],
    "elk_stack": ["ELK", "ELK Stack", "Elastic Stack"],
    "keras": ["Keras", "keras"],
    "pascal": ["Pascal", "pascal"],
    "scheme": ["Scheme", "scheme"],
    "apache_spark": ["Apache Spark", "Spark"],
    "forth": ["Forth", "forth"],
    "mxnet": ["MXNet", "mxnet", "Apache MXNet"],
    "matplotlib": ["Matplotlib", "plt", "matplotlib"],
    "bash": ["Bash", "bash", "Bash Scripting", "Shell Bash"],
    "firestore": ["Firestore", "Google Firestore", "Cloud Firestore"],
    "microservices": ["Microservices", "Microservice Architecture", "Microservices Architecture"],
    "couchdb": ["CouchDB", "Apache CouchDB", "couchdb"],
    "fastapi": ["FastAPI", "fastapi"],
    "kotlin_multiplatform": ["Kotlin Multiplatform", "KMP", "kotlin multiplatform"],
    "influxdb": ["InfluxDB", "influxdb"],
    "data_warehousing": ["Data Warehousing", "Data Warehouse"],
    "storybook": ["Storybook", "storybook.js", "storybook"],
    "bootstrap": ["Bootstrap", "bootstrap"],
    "rag": ["RAG", "Retrieval-Augmented Generation", "RAG (Retrieval-Augmented Generation)"],
    "bitbucket": ["Bitbucket", "bitbucket"],
    "groovy": ["Groovy", "groovy"],
    "react_native": ["React Native", "react-native", "react native"],
    "integration_testing": ["Integration Testing", "integration testing"],
    "kubernetes": ["Kubernetes", "k8s", "kubernetes"],
    "code_review": ["Code Review", "Code Review Practices", "Peer Review"],
    "gitlab_ci_cd": ["GitLab CI/CD", "GitLab CI", "GitLab Pipelines"],
    "linkerd": ["Linkerd", "linkerd"],
    "security": ["Security", "App Security", "System Security"],
    "auditing": ["Auditing", "Audit", "System Auditing"],
    "react": ["React", "React.js", "ReactJS", "react"],
    "node": ["Node", "Node.js", "NodeJS", "node"],
    "javascript": ["JavaScript", "JS", "javascript"],
    "typescript": ["TypeScript", "TS", "typescript"],
    "python": ["Python", "python"],
    "java": ["Java", "java", "JVM"],
    "csharp": ["C#", "CSharp", "csharp"],
    "cpp": ["C++", "CPP", "c++", "cpp"],
    "c": ["C", "ANSI C", "c language"],
    "php": ["PHP", "php"],
    "ruby": ["Ruby", "ruby", "Ruby on Rails", "RoR"],
    "golang": ["Go", "Golang", "go"],
    "kotlin": ["Kotlin", "kotlin"],
    "swift": ["Swift", "swift"],
    "r": ["R", "R Language", "R programming"],
    "scala": ["Scala", "scala"],
    "perl": ["Perl", "perl"],
    "matlab": ["MATLAB", "Matlab", "matlab"],
    "dart": ["Dart", "dart"],
    "flutter": ["Flutter", "flutter"],
    "laravel": ["Laravel", "laravel"],
    "django": ["Django", "django"],
    "flask": ["Flask", "flask"],
    "fastapi": ["FastAPI", "fastapi"],
    "spring": ["Spring", "Spring Boot", "spring"],
    "express": ["Express", "Express.js", "ExpressJS", "express"],
    "angular": ["Angular", "AngularJS", "angular"],
    "vue": ["Vue", "Vue.js", "VueJS", "vue"],
    "svelte": ["Svelte", "svelte"],
    "nextjs": ["Next.js", "NextJS", "nextjs"],
    "nuxtjs": ["Nuxt.js", "NuxtJS", "nuxtjs"],
    "ember": ["Ember", "Ember.js", "emberjs"],
    "backbone": ["Backbone", "Backbone.js", "backbonejs"],
    "jquery": ["jQuery", "jquery"],
    "html": ["HTML", "HTML5", "html"],
    "css": ["CSS", "CSS3", "css"],
    "sass": ["Sass", "SASS", "scss"],
    "tailwind": ["Tailwind", "TailwindCSS", "tailwind"],
    "bootstrap": ["Bootstrap", "bootstrap"],
    "materialui": ["Material UI", "MUI", "material-ui"],
    "mongodb": ["MongoDB", "mongo", "mongodb"],
    "mysql": ["MySQL", "mysql"],
    "postgresql": ["PostgreSQL", "Postgres", "postgres"],
    "sqlite": ["SQLite", "sqlite"],
    "oracle": ["Oracle", "Oracle DB", "oracle database"],
    "mariadb": ["MariaDB", "mariadb"],
    "redis": ["Redis", "redis"],
    "cassandra": ["Cassandra", "Apache Cassandra"],
    "elasticsearch": ["Elasticsearch", "elastic search"],
    "neo4j": ["Neo4j", "neo4j graph"],
    "firebase": ["Firebase", "firebase"],
    "supabase": ["Supabase", "supabase"],
    "graphql": ["GraphQL", "graphql"],
    "restapi": ["REST API", "RESTful", "restapi"],
    "soap": ["SOAP", "soap api"],
    "grpc": ["gRPC", "grpc"],
    "docker": ["Docker", "docker"],
    "kubernetes": ["Kubernetes", "k8s", "kubernetes"],
    "jenkins": ["Jenkins", "jenkins"],
    "git": ["Git", "git"],
    "github": ["GitHub", "github"],
    "gitlab": ["GitLab", "gitlab"],
    "bitbucket": ["Bitbucket", "bitbucket"],
    "ci_cd": ["CI/CD", "Continuous Integration", "Continuous Delivery"],
    "ansible": ["Ansible", "ansible"],
    "terraform": ["Terraform", "terraform"],
    "puppet": ["Puppet", "puppet"],
    "chef": ["Chef", "chef"],
    "prometheus": ["Prometheus", "prometheus"],
    "grafana": ["Grafana", "grafana"],
    "elk": ["ELK Stack", "Elastic Stack", "elk"],
    "splunk": ["Splunk", "splunk"],
    "nagios": ["Nagios", "nagios"],
    "sonarqube": ["SonarQube", "sonarqube"],
    "linux": ["Linux", "linux", "unix"],
    "ubuntu": ["Ubuntu", "ubuntu"],
    "centos": ["CentOS", "centos"],
    "windows": ["Windows", "windows server"],
    "macos": ["macOS", "Mac OS", "osx"],
    "bash": ["Bash", "Shell Scripting", "bash"],
    "powershell": ["PowerShell", "powershell"],
    "zsh": ["Zsh", "z shell"],
    "agile": ["Agile", "Agile Methodology"],
    "scrum": ["Scrum", "scrum master"],
    "kanban": ["Kanban", "kanban"],
    "waterfall": ["Waterfall", "waterfall methodology"],
    "jira": ["Jira", "jira"],
    "confluence": ["Confluence", "confluence"],
    "trello": ["Trello", "trello"],
    "asana": ["Asana", "asana"],
    "slack": ["Slack", "slack"],
    "notion": ["Notion", "notion"],
    "microsoft_teams": ["Microsoft Teams", "Teams"],
    "zoom": ["Zoom", "zoom"],
    "figma": ["Figma", "figma"],
    "sketch": ["Sketch", "sketch"],
    "adobe_xd": ["Adobe XD", "xd"],
    "photoshop": ["Photoshop", "Adobe Photoshop"],
    "illustrator": ["Illustrator", "Adobe Illustrator"],
    "indesign": ["InDesign", "Adobe InDesign"],
    "tensorflow": ["TensorFlow", "tensorflow"],
    "pytorch": ["PyTorch", "torch", "pytorch", "Py Torch"],
    "keras": ["Keras", "keras"],
    "scikitlearn": ["Scikit-learn", "sklearn", "scikit learn"],
    "theano": ["Theano", "theano"],
    "mxnet": ["MXNet", "mxnet"],
    "huggingface": ["Hugging Face", "Transformers", "huggingface"],
    "langchain": ["LangChain", "langchain"],
    "rag": ["RAG", "Retrieval Augmented Generation"],
    "openai": ["OpenAI", "open ai"],
    "nlp": ["NLP", "Natural Language Processing"],
    "cv": ["Computer Vision", "cv"],
    "speech_recognition": ["Speech Recognition", "ASR"],
    "reinforcement_learning": ["Reinforcement Learning", "RL"],
    "mlops": ["MLOps", "mlops"],
    "data_mining": ["Data Mining", "data mining"],
    "feature_engineering": ["Feature Engineering", "feature engineering"],
    "data_preprocessing": ["Data Preprocessing", "data preprocessing"],
    "model_deployment": ["Model Deployment", "ml deployment"],
    "model_serving": ["Model Serving", "ml serving"],
    "bigdata": ["Big Data", "bigdata"],
    "hadoop": ["Hadoop", "apache hadoop"],
    "spark": ["Apache Spark", "spark"],
    "hive": ["Hive", "apache hive"],
    "pig": ["Pig", "apache pig"],
    "flink": ["Flink", "apache flink"],
    "kafka": ["Kafka", "Apache Kafka"],
    "airflow": ["Airflow", "Apache Airflow"],
    "beam": ["Apache Beam", "beam"],
    "storm": ["Apache Storm", "storm"],
    "databricks": ["Databricks", "databricks"],
    "snowflake": ["Snowflake", "snowflake"],
    "redshift": ["Amazon Redshift", "redshift"],
    "bigquery": ["BigQuery", "Google BigQuery"],
    "etl": ["ETL", "Extract Transform Load"],
    "data_pipeline": ["Data Pipeline", "data pipelines"],
    "data_lake": ["Data Lake", "datalake"],
    "data_warehouse": ["Data Warehouse", "data warehouse"],
    "nosql": ["NoSQL", "nosql databases"],
    "olap": ["OLAP", "Online Analytical Processing"],
    "cybersecurity": ["Cybersecurity", "cyber security"],
    "networking": ["Networking", "computer networks"],
    "firewalls": ["Firewalls", "firewall"],
    "ids_ips": ["IDS/IPS", "Intrusion Detection", "Intrusion Prevention"],
    "wireshark": ["Wireshark", "wireshark"],
    "nmap": ["Nmap", "nmap"],
    "burpsuite": ["Burp Suite", "burpsuite"],
    "metasploit": ["Metasploit", "metasploit"],
    "kali": ["Kali Linux", "kali"],
    "ethical_hacking": ["Ethical Hacking", "pentesting", "penetration testing"],
    "cryptography": ["Cryptography", "encryption"],
    "blockchain": ["Blockchain", "block chain"],
    "web3": ["Web3", "web 3"],
    "solidity": ["Solidity", "solidity"],
    "smartcontracts": ["Smart Contracts", "smart contract"],
    "dapps": ["DApps", "Decentralized Applications"],
    "nft": ["NFT", "Non-Fungible Tokens"],
    "defi": ["DeFi", "Decentralized Finance"],
    "cryptocurrency": ["Cryptocurrency", "crypto"],
    "bitcoin": ["Bitcoin", "btc"],
    "ethereum": ["Ethereum", "eth"],
    "hyperledger": ["Hyperledger", "hyperledger"],
    "corda": ["Corda", "corda blockchain"],
    "unity": ["Unity", "unity3d"],
    "unreal": ["Unreal Engine", "unreal"],
    "godot": ["Godot", "godot engine"],
    "blender": ["Blender", "blender3d"],
    "maya": ["Maya", "autodesk maya"],
    "3dsmax": ["3ds Max", "autodesk 3dsmax"],
    "vr": ["Virtual Reality", "VR"],
    "ar": ["Augmented Reality", "AR"],
    "xr": ["Extended Reality", "XR"],
    "oculus": ["Oculus", "meta quest"],
    "hololens": ["HoloLens", "microsoft hololens"],
    "android": ["Android", "android development"],
    "ios": ["iOS", "ios development"],
    "flutter": ["Flutter", "flutter"],
    "reactnative": ["React Native", "reactnative"],
    "kotlin": ["Kotlin", "kotlin"],
    "swift": ["Swift", "swift"],
    "objectivec": ["Objective-C", "objc"],
    "dart": ["Dart", "dart"],
    "cordova": ["Cordova", "apache cordova"],
    "phonegap": ["PhoneGap", "phonegap"],
    "xamarin": ["Xamarin", "xamarin"],
    "ionic": ["Ionic", "ionic framework"],
    "qa": ["Quality Assurance", "QA"],
    "testing": ["Software Testing", "testing"],
    "selenium": ["Selenium", "selenium"],
    "junit": ["JUnit", "junit"],
    "pytest": ["PyTest", "pytest"],
    "cypress": ["Cypress", "cypress"],
    "mocha": ["Mocha", "mocha"],
    "chai": ["Chai", "chai"],
    "jest": ["Jest", "jest"],
    "karma": ["Karma", "karma"],
    "postman": ["Postman", "postman"],
    "restassured": ["REST Assured", "restassured"],
    "soapui": ["SoapUI", "soapui"],
    "locust": ["Locust", "locust.io"],
    "gatling": ["Gatling", "gatling"],
    "loadrunner": ["LoadRunner", "loadrunner"],
    "jmeter": ["JMeter", "Apache JMeter", "jmeter"],
    "integration_testing": ["Integration Testing", "integration tests"],
    "unit_testing": ["Unit Testing", "unit tests"],
    "e2e_testing": ["E2E Testing", "end to end testing"],
    "bdd": ["BDD", "Behavior Driven Development"],
    "tdd": ["TDD", "Test Driven Development"],
    "static_code_analysis": ["Static Code Analysis", "static analysis"],
    "code_review": ["Code Review", "code reviews"],
    "refactoring": ["Refactoring", "refactoring techniques"],
    "clean_code": ["Clean Code", "clean coding"],
    "design_patterns": ["Design Patterns", "design pattern"],
    "oop": ["OOP", "Object Oriented Programming"],
    "functional_programming": ["Functional Programming", "fp"],
    "solid": ["SOLID Principles", "solid"],
    "agile": ["Agile Methodologies", "Agile"],
    "scrum": ["Scrum", "scrum"],
    "kanban": ["Kanban", "kanban"],
    "pair_programming": ["Pair Programming", "pair programming"],
    "devops": ["DevOps", "devops"],
    "cicd": ["CI/CD", "Continuous Integration", "Continuous Delivery", "cicd"],
    "jenkins": ["Jenkins", "jenkins"],
    "travisci": ["Travis CI", "TravisCI"],
    "circleci": ["CircleCI", "circleci"],
    "gitlabci": ["GitLab CI/CD", "gitlab ci"],
    "githubactions": ["GitHub Actions", "github actions"],
    "azuredevops": ["Azure DevOps", "azure devops"],
    "ansible": ["Ansible", "ansible"],
    "chef": ["Chef", "chef"],
    "puppet": ["Puppet", "puppet"],
    "terraform": ["Terraform", "terraform"],
    "pulumi": ["Pulumi", "pulumi"],
    "cloudformation": ["CloudFormation", "AWS CloudFormation"],
    "argocd": ["ArgoCD", "argo cd"],
    "helm": ["Helm", "kubernetes helm"],
    "vault": ["HashiCorp Vault", "vault"],
    "consul": ["Consul", "hashicorp consul"],
    "docker": ["Docker", "docker"],
    "kubernetes": ["Kubernetes", "k8s"],
    "linkerd": ["Linkerd", "linkerd"],
    "istio": ["Istio", "istio"],
    "service_mesh": ["Service Mesh", "servicemesh"],
    "microservices": ["Microservices", "microservices architecture"],
    "monorepo": ["Monorepo Management", "monorepos"],
    "git": ["Git", "git"],
    "github": ["GitHub", "github"],
    "gitlab": ["GitLab", "gitlab"],
    "bitbucket": ["Bitbucket", "bitbucket"],
    "sourcetree": ["SourceTree", "sourcetree"],
    "version_control": ["Version Control", "vcs"],
    "mercurial": ["Mercurial", "hg"],
    "svn": ["SVN", "Subversion"],
    "project_management": ["Project Management", "pm tools"],
    "jira": ["Jira", "jira"],
    "trello": ["Trello", "trello"],
    "asana": ["Asana", "asana"],
    "confluence": ["Confluence", "confluence"],
    "notion": ["Notion", "notion"],
    "slack": ["Slack", "slack"],
    "msteams": ["Microsoft Teams", "ms teams"],
    "zoom": ["Zoom", "zoom"],
    "skype": ["Skype", "skype"],
    "googlemeet": ["Google Meet", "google meet"],
    "salesforce": ["Salesforce", "salesforce"],
    "sap": ["SAP Cloud", "SAP"],
    "oraclecloud": ["Oracle Cloud", "oracle cloud"],
    "ibmcloud": ["IBM Cloud", "ibm cloud"],
    "alibabacloud": ["Alibaba Cloud", "alibaba cloud"],
    "aws": ["AWS", "Amazon Web Services"],
    "gcp": ["GCP", "Google Cloud Platform"],
    "azure": ["Azure", "Microsoft Azure"],
    "vmware": ["VMware Cloud", "vmware"],
    "network_security": ["Network Security", "network security"],
    "siem": ["SIEM", "Security Information and Event Management"],
    "soc": ["SOC Operations", "Security Operations Center"],
    "ids": ["IDS", "Intrusion Detection System"],
    "ips": ["IPS", "Intrusion Prevention System"],
    "owasp": ["OWASP", "Open Web Application Security Project"],
    "owaspzap": ["OWASP ZAP", "zap proxy"],
    "threat_modeling": ["Threat Modeling", "threat modeling"],
    "pentesting": ["Penetration Testing", "pen testing"],
    "auditing": ["Auditing", "security auditing"],
    "compliance": ["Compliance", "security compliance"],
    "gdpr": ["GDPR", "General Data Protection Regulation"],
    "hipaa": ["HIPAA", "hipaa compliance"],
    "pci": ["PCI DSS", "pci compliance"],
    "iso27001": ["ISO 27001", "iso 27001"],
    "security": ["Security", "appsec", "cybersecurity"],
    "cryptography": ["Cryptography", "crypto"],
    "idsips": ["IDS/IPS", "intrusion detection", "intrusion prevention"],
    "firewall": ["Firewall", "firewalls"],
    "vpn": ["VPN", "virtual private network"],
    "zerotrust": ["Zero Trust", "zero trust security"],
    "dast": ["DAST", "Dynamic Application Security Testing"],
    "sast": ["SAST", "Static Application Security Testing"],
    "iast": ["IAST", "Interactive Application Security Testing"],
    "siemtools": ["SIEM Tools", "siem"],
    "forensics": ["Digital Forensics", "cyber forensics"],
    "incident_response": ["Incident Response", "ir"],
    "ml": ["Machine Learning", "ML", "machine learning"],
    "dl": ["Deep Learning", "DL", "deep learning"],
    "rl": ["Reinforcement Learning", "RL", "reinforcement learning"],
    "cv": ["Computer Vision", "cv"],
    "nlp": ["NLP", "Natural Language Processing"],
    "speech_recognition": ["Speech Recognition", "speech to text"],
    "openai": ["OpenAI APIs", "openai"],
    "langchain": ["LangChain", "langchain"],
    "rag": ["RAG", "Retrieval Augmented Generation"],
    "huggingface": ["Hugging Face Transformers", "huggingface"],
    "tensorflow": ["TensorFlow", "tensorflow"],
    "pytorch": ["PyTorch", "pytorch"],
    "keras": ["Keras", "keras"],
    "scikitlearn": ["Scikit-learn", "sklearn"],
    "mlflow": ["MLflow", "mlflow"],
    "onnx": ["ONNX", "onnx"],
    "openai_gym": ["OpenAI Gym", "gym"],
    "dvc": ["DVC", "Data Version Control"],
    "dataengineering": ["Data Engineering", "data engineering"],
    "etl": ["ETL Pipelines", "ETL", "extract transform load"],
    "datawarehousing": ["Data Warehousing", "data warehouse"],
    "datalakes": ["Data Lakes", "data lake"],
    "datamodeling": ["Data Modeling", "data models"],
    "bigdata": ["Big Data", "bigdata"],
    "hadoop": ["Hadoop", "apache hadoop"],
    "spark": ["Apache Spark", "spark"],
    "flink": ["Apache Flink", "flink"],
    "airflow": ["Apache Airflow", "airflow"],
    "kafka": ["Apache Kafka", "kafka"],
    "pulsar": ["Apache Pulsar", "pulsar"],
    "mahout": ["Apache Mahout", "mahout"],
    "databricks": ["Databricks", "databricks"],
    "snowflake": ["Snowflake", "snowflake"],
    "redshift": ["Amazon Redshift", "redshift"],
    "bigquery": ["Google BigQuery", "bigquery"],
    "tableau": ["Tableau", "tableau"],
    "qlikview": ["QlikView", "qlikview"],
    "powerbi": ["Power BI", "powerbi"],
    "Nest.Js": ["nest", "nest.js", "nestjs"],
    "Electron.js": ["electron", "electron.js", "electronjs"], 
    "Molecular.js": ["molecular", "molecular.js", "molecularjs"]
}

import spacy
from spacy.matcher import PhraseMatcher


class SkillExtractor:
    def __init__(self, skills_list, skills_expansions=None):
        """
        :param skills_list: List of base skills (e.g., ["python", "java"])
        :param skills_expansions: Dict mapping skill -> list of expansions/synonyms
                                  e.g., {"python": ["python3", "py"], "java": ["java se", "java ee"]}
        """
        self.nlp = spacy.load("en_core_web_sm")
        self.matcher = PhraseMatcher(self.nlp.vocab, attr="LOWER")
        self.skills_list = skills_list
        self.skills_expansions = skills_expansions or {}
        self._build_matcher()

    def _build_matcher(self):
        """Builds PhraseMatcher patterns."""
        for skill in self.skills_list:
            expansions = self.skills_expansions.get(skill, [skill])
            patterns = [self.nlp.make_doc(term) for term in expansions]
            self.matcher.add(skill, patterns)

    def extract(self, text: str):
        """Extract skills from given text."""
        doc = self.nlp(text)
        found_skills = {
            self.nlp.vocab.strings[match_id] for match_id, start, end in self.matcher(doc)
        }
        return list(found_skills)

# extractor = SkillExtractor(skills_list, skills_expansions)
# print(extractor.extract("""Node"""))




